### ISSUE TITLE
CPU Issue

### ISSUE THREAD

**Issue by davidlesches** [brainopia/sidekiq-limit_fetch#63]
sidekiq-limit_fetch 3.0.1 (with sidekiq 4) is throwing my CPU into overdrive - to 105%.

sidekiq 4 without sidekiq-limit_fetch doesn't do this, and sidekiq 3 with sidekiq-limit_fetch 2.4.2 works fine as well. It's only 4 + limit_fetch.

I'm running El Capitan. Let me know if there is anything I can test for you to help with this. I love this gem! Thanks

**Comment by schaerli** [comment]
+1

**Comment by arrowcircle** [comment]
+1

**Comment by 907th** [comment]
Confirm

**Comment by newtonik25** [comment]
+1, for example I have 4 processes in sidekiq for 100% cpu each, and one sidekiq-limit_fetch process, which have 50% cpu, so I think it must be 10-15 max, but not 50 percents.

**Comment by Yoshyn** [comment]
+1, does not work well with sidekiq 4+. No problem with 3+

**Comment by hSATAC** [comment]
+1 to this.

**Comment by hSATAC** [comment]
I've found a workaround for this, it's looking good now if any of you want to try this:

I noticed that this high cpu only appears when your sidekiq listen to single queue, which is the default behavior of sidekiq.

If your sidekiq listen to more than 1 queue, the cpu load is back to normal.

For example: `sidekiq -q default,3, -q empty,1 -c 25`

By adding an empty queue, the sidekiq behaviors normal again.

**Comment by brancusi** [comment]
+1

**Comment by grahamlyons** [comment]
I'm seeing the same behaviour using sidekiq (4.1.1) and sidekiq-limit_fetch (3.1.0).

Is this something you're looking at @brainopia?

**Comment by d4rky-pl** [comment]
@hSATAC it seems that your workaround didn't help our case after all so I'm +1 this issue and downgrading to sidekiq 3.x

**Comment by jwilf** [comment]
+1

**Comment by alexsotocx** [comment]
+1

**Comment by d4rky-pl** [comment]
I have managed to narrow it down to single offending line of code. I've prepared [demo app](https://github.com/d4rky-pl/sidekiq-limit_fetch-bug) that reproduces the issue.

The problem is in `lib/sidekiq/limit_fetch.rb`:

```
 def retrieve_work
  queue, job = redis_brpop *Queues.acquire, Sidekiq::BasicFetch::TIMEOUT # <-- this line
   Queues.release_except(queue)
   UnitOfWork.new(queue, job) if job
 end
```

For some reason BRPOP does not like it when it's being run in more than one thread. I wish I could send a pull request but that's as far as my Redis knowledge goes and I have no idea (yet) how to fix that.

I will try investigating it further and see if I manage to solve this.

**Comment by d4rky-pl** [comment]
Oh, I forgot the most important bit: The difference in what is happening is that when there's more than one sidekiq thread, the BRPOP command for some reason stops blocking so this method is being run like crazy with 0 timeout, causing CPU spike.

**Comment by d4rky-pl** [comment]
OK, that BRPOP was a total red herring :) Seems that @grahamlyons was closest to the truth as the problem is with the LUA script called redis_acquire_script in `lib/sidekiq/limit_fetch/global/selector.rb`. When there's more than one thread the script does not return list of queues which causes the previously found method `redis_brpop` to short-circuit as the number of arguments is less than 2.

**Comment by 907th** [comment]
@d4rky-pl @grahamlyons Please, take a look at #73

**Comment by brainopia** [comment]
Big thanks and happy release to everyone :christmas_tree:
